apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-2fdc10825cc94f45a7110f9ed03ccf7c-depl
  labels:
    app: coll-2fdc10825cc94f45a7110f9ed03ccf7c
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-2fdc10825cc94f45a7110f9ed03ccf7c
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-2fdc10825cc94f45a7110f9ed03ccf7c
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-2fdc10825cc94f45a7110f9ed03ccf7c
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-2fdc10825cc94f45a7110f9ed03ccf7c
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping